on:
  issues:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: donPain/hello-world-javascript-action@v1.6
        with:
          who-to-greet: 'Olá eduardo'
    
